#!/usr/bin/env bash
# Måske lidt overgjort? 

selekt(){
   printf '%s' "Søger.."; get="$1"; shift

   ((i=1)); while read -r linje;do
      ssid_enkelt="${linje#"${linje%%[^"$get":[:space:]]*}"}"
      space=""; ((i<10)) && space=" "
      printf '\e[K\r%s%s\n' "$i: $space" "$ssid_enkelt"
      declare -a ssid; IFS=$'\n' ssid+=($ssid_enkelt); ((i++))
   done < <(nmcli -f "$get" -m multiline "${@}")

   read -rp "[1-$((i-1))]: "
   printf '%s\n' "${ssid[((REPLY-1))]}"
}

[[ "$@" ]] && selekt $@
